name: FourSeason
author: DanielFlow
version: 1.3.2
main: de.fourseasons.server.SeasonSystem.SeasonSystem

commands:
  help:
    aliases: [info, hilfe, h]
  feed:
    aliases: [eat, essen, food]
  globalmute:
    aliases: [chatmute, muteall, chatsperren]
  pvp:
    aliases: [globalgod, nopvp, grace]
  wartung:
    aliases: [maintenance, wartungen, whitelist]
  team:
    aliases: [staff, t, teamler, ask]
  heal:
    aliases: [heilen, heel, heilung, ih]
  tpa:
  tpaccept:
  setspawn:
  spawn:
    aliases: [s, spawnpoint, sp]
  gamemode:
    aliases: [gm, gmode, changemode, changegm, switchmode]